In [96]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [97]:
dataset=pd.read_excel(r'C:\Users\user\Accident_data\Acc_data_version2 - Copy.xlsx')

In [77]:
pwd

'C:\\Users\\user\\Accident_data'

In [98]:
dataset.head()

,State,Accidents risk,Day,Day risk scale,Time,Time risk scale,Weather,Weather risk scale,Age,Age risk scale,...,Cost % Of Commodity Damage,Packed_in,VEHICLE_TYPE,WEIGHT_CAPACITY(METRIC_TON),COMMODITY WEIGHT,OVERLOAD,OVERLOAD SCALE,VEHICLE_HEALTH,VEHICLE HEALTH SCALE,ACCIDENT RISK PERCENTAGE
0,Andhra Pradesh,3.5,Monday,3.5,6am to 10pm,3.5,Foggy,4.0,18-25,5.0,...,0.7,Cardboard_Packing,Light COMMERCIAL Vehicles (TATA ACE),1.5,2.0,33.333333,6,Bad,9,50.000
1,Andhra Pradesh,3.5,Tuesday,2.0,10am to 8pm,2.5,Rainy,3.5,25-35,3.5,...,0.7,Plastic_Packing,14 FT DCM,5.0,4.0,-20.000000,1,Medium,5,28.750
2,Andhra Pradesh,3.5,Wednesday,2.0,10pm to 8am,5.0,Sunny,2.0,35-55,3.0,...,0.2,Plastic_Packing,17 FT DCM,5.5,5.0,-9.090909,1,Good,3,28.125
3,Andhra Pradesh,3.5,Thursday,2.0,6am to 10pm,3.5,Foggy,4.0,Above 55,2.5,...,0.7,Cardboard_Packing,19 FT DCM,7.5,7.0,-6.666667,1,Bad,9,45.000
4,Andhra Pradesh,3.5,Friday,3.0,10am to 8pm,2.5,Rainy,3.5,18-25,5.0,...,0.4,Cardboard_Packing,18 FT Lorry - 6 WHEELS,9.0,8.0,-11.111111,1,Medium,5,33.125

In [99]:
dataset=dataset.drop(["State","Day","Time","Weather","Age","Vehicle_Age","COMMODITY","Cost % Of Commodity Damage","Packed_in","VEHICLE_TYPE","WEIGHT_CAPACITY(METRIC_TON)","COMMODITY WEIGHT","VEHICLE_HEALTH"],axis=1)

In [82]:
dataset

,Accidents risk,Day risk scale,Time risk scale,Weather risk scale,Age risk scale,Vehicle Age risk scale,OVERLOAD SCALE,VEHICLE HEALTH SCALE,ACCIDENT RISK PERCENTAGE
0,3.5,3.5,3.5,4.0,5.0,3.0,6,9,50.000
1,3.5,2.0,2.5,3.5,3.5,2.0,1,5,28.750
2,3.5,2.0,5.0,2.0,3.0,3.0,1,3,28.125
3,3.5,2.0,3.5,4.0,2.5,3.5,1,9,45.000
4,3.5,3.0,2.5,3.5,5.0,3.0,1,5,33.125
5,3.5,3.5,5.0,2.0,3.5,2.0,1,3,29.375
6,3.5,3.5,3.5,4.0,3.0,3.0,1,9,38.125
7,3.5,3.5,2.5,3.5,2.5,3.5,1,5,31.250
8,3.5,2.0,5.0,2.0,5.0,3.0,1,3,30.625
9,3.5,2.0,3.5,4.0,3.5,2.0,1,9,35.625
10,3.5,2.0,2.5,3.5,3.0,3.0,1,5,29.375
11,3.5,3.0,5.0,2.0,2.5,3.5,1,3,29.375
12,3.5,3.5,3.5,4.0,5.0,3.0,1,9,40.625
13,3.5,3.5,2.5,3.5,3.5,2.0,9,5,40.625
14,3.5,3.5,5.0,2.0,3.0,3.0,1,3,30.000
15,3.5,2.0,3.5,4.0,2.5,3.5,1,9,40.000
16,3.5,2.0,2.5,3.5,5.0,3.0,1,5,31.875
17,3.5,2.0,5.0,2.0,3.5,2.0,1,3,27.500
18,3.5,3.0,3.5,4.0,3.0,3.0,1,9,37.500
19,3.5,3.5,2.5,3.5,2.5,3.5,1,5,31.250
20,3.5,3.5,5.0,2.0,5.0,3.0,1,3,32.500
21,3.5,3.5,3.5,4.0,3.5,2.0,1,9,42.000
22,3.5,2.0,2.5,3.5,3.0,3.0,6,5,35.625
23,2.0,2.0,5.0,2.0,2.5,3.5,6,3,32.500
24,2.0,2.0,3.5,4.0,5.0,3.0,1,9,55.000
25,2.0,3.0,2.5,3.5,3.5,2.0,1,5,28.125
26,2.0,3.5,5.0,2.0,3.0,3.0,1,3,28.125
27,2.0,3.5,3.5,4.0,2.5,3.5,1,9,36.250
28,2.0,3.5,2.5,3.5,5.0,3.0,6,5,38.125
29,2.0,2.0,5.0,2.0,3.5,2.0,1,3,25.625
...,...,...,...,...,...,...,...,...,...
1307,2.5,3.5,2.5,4.5,3.0,3.0,1,5,36.000
1308,5.0,3.5,3.5,5.0,5.0,3.0,6,9,65.000
1309,5.0,3.5,2.5,5.0,3.5,2.0,1,5,32.000
1310,5.0,3.5,5.0,4.0,3.0,3.0,1,3,33.000
1311,5.0,2.0,3.5,5.0,2.5,3.5,1,9,39.375
1312,5.0,2.0,2.5,5.0,5.0,3.0,1,5,35.625
1313,5.0,2.0,5.0,4.5,3.5,2.0,1,3,34.000
1314,5.0,3.0,3.5,4.0,3.0,3.0,1,9,42.000
1315,4.5,2.0,2.5,4.0,3.0,3.0,1,5,32.000
1316,4.5,3.0,5.0,5.0,2.5,3.5,1,3,34.375
1317,4.5,3.5,3.5,4.0,5.0,3.0,1,9,45.000
1318,4.5,3.5,2.5,4.5,3.5,2.0,1,5,33.125
1319,4.5,3.5,5.0,5.0,3.0,3.0,1,3,33.000
1320,4.5,2.0,3.5,4.0,2.5,3.5,1,9,43.000
1321,4.5,2.0,2.5,4.5,5.0,3.0,1,5,34.375
1322,3.0,2.0,2.5,4.0,2.5,3.5,1,5,29.375
1323,3.0,3.0,5.0,5.0,5.0,3.0,1,3,35.000
1324,3.0,3.5,3.5,5.0,3.5,2.0,1,9,44.000
1325,3.0,3.5,2.5,5.0,3.0,3.0,1,5,32.500
1326,3.0,3.5,5.0,4.0,2.5,3.5,1,3,31.875
1327,3.0,2.0,3.5,4.5,5.0,3.0,1,9,55.000
1328,3.0,2.0,2.5,5.0,3.5,2.0,9,5,50.000
1329,4.5,3.5,2.5,4.0,2.5,3.5,1,5,33.125
1330,4.5,3.5,5.0,4.5,5.0,3.0,1,3,36.875
1331,4.5,3.5,3.5,4.0,3.5,2.0,1,9,38.750
1332,4.5,2.0,2.5,5.0,3.0,3.0,1,5,32.500
1333,4.5,2.0,5.0,5.0,2.5,3.5,1,3,33.125
1334,4.5,2.0,3.5,4.0,5.0,3.0,1,9,40.000
1335,4.5,3.0,2.5,4.5,3.5,2.0,1,5,32.500
1336,4.5,4.0,3.0,4.0,4.0,4.0,1,5,36.000

In [100]:
dataset=dataset.drop('OVERLOAD',axis=1)

In [101]:
X=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])

In [9]:
type(X)

pandas.core.frame.DataFrame

In [10]:
type(y)

pandas.core.frame.DataFrame

In [11]:
type(X_train)

NameError: name 'X_train' is not defined

In [ ]:
type(y_train)

In [102]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1336 entries, 0 to 1335
Data columns (total 9 columns):
Accidents risk              1336 non-null float64
Day risk scale              1336 non-null float64
Time risk scale             1336 non-null float64
Weather risk scale          1336 non-null float64
Age risk scale              1336 non-null float64
Vehicle Age risk scale      1336 non-null float64
OVERLOAD SCALE              1336 non-null int64
VEHICLE HEALTH SCALE        1336 non-null int64
ACCIDENT RISK PERCENTAGE    1336 non-null float64
dtypes: float64(7), int64(2)
memory usage: 94.0 KB

In [104]:
dataset['OVERLOAD SCALE'] = dataset['OVERLOAD SCALE'].astype(float)

In [105]:
dataset['VEHICLE HEALTH SCALE'] = dataset['VEHICLE HEALTH SCALE'].astype(float)

In [106]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1336 entries, 0 to 1335
Data columns (total 9 columns):
Accidents risk              1336 non-null float64
Day risk scale              1336 non-null float64
Time risk scale             1336 non-null float64
Weather risk scale          1336 non-null float64
Age risk scale              1336 non-null float64
Vehicle Age risk scale      1336 non-null float64
OVERLOAD SCALE              1336 non-null float64
VEHICLE HEALTH SCALE        1336 non-null float64
ACCIDENT RISK PERCENTAGE    1336 non-null float64
dtypes: float64(9)
memory usage: 94.0 KB

In [84]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [68]:
X_test=X.iloc[1336:]

In [69]:
X_test

,Accidents risk,Day risk scale,Time risk scale,Weather risk scale,Age risk scale,Vehicle Age risk scale,OVERLOAD,OVERLOAD SCALE,VEHICLE HEALTH SCALE
1336,4.5,4.0,3.0,4.0,4.0,4.0,4.0,1,5

In [85]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(min_samples_split=4,max_depth=25)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=25, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=4, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [86]:
y_pred = regressor.predict(X_test)

In [87]:
y_pred[30:35]

array([36.875     , 28.125     , 29.375     , 34.85714286, 30.        ])

In [88]:
y_test[30:35]

      ACCIDENT RISK PERCENTAGE
54                      36.875
950                     28.125
1088                    29.375
45                      33.750
988                     30.000

In [36]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [37]:
y_pred = regressor.predict(X_test)

In [38]:
y_pred[30:35]

array([[38.79853623],
       [27.26065976],
       [28.92546799],
       [36.92896295],
       [30.26894712]])

In [39]:
y_test[30:35]

      ACCIDENT RISK PERCENTAGE
54                      36.875
950                     28.125
1088                    29.375
45                      33.750
988                     30.000

In [40]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 1.8537386698289815
Mean Squared Error: 12.072135806241691
Root Mean Squared Error: 3.4744979214617024

In [42]:
import pickle 
  
# Save the trained model as a pickle string. 
model= pickle.dumps(regressor)

In [43]:
regressor_from_pickle = pickle.loads(model)

In [44]:
regressor_from_pickle.predict(X_test)

array([[32.23720913],
       [38.24400031],
       [37.82728352],
       [28.06541123],
       [37.78924736],
       [29.95504773],
       [37.07153577],
       [33.45020749],
       [31.13618469],
       [26.77513836],
       [47.52654389],
       [31.50116584],
       [27.68647111],
       [46.42409388],
       [33.69048785],
       [37.85112137],
       [27.31233497],
       [36.96015792],
       [39.81849382],
       [37.26506317],
       [29.03635983],
       [31.32591201],
       [36.95430886],
       [27.66619511],
       [31.79221115],
       [28.95909698],
       [30.76202862],
       [30.42817145],
       [29.00786297],
       [40.87227956],
       [38.79853623],
       [27.26065976],
       [28.92546799],
       [36.92896295],
       [30.26894712],
       [36.58847665],
       [31.79390064],
       [29.32367686],
       [26.36805429],
       [38.16796257],
       [54.17818148],
       [40.42033321],
       [29.24536214],
       [29.4443652 ],
       [27.58700569],
       [26.55097418],
       [37.80719955],
       [40.02018981],
       [39.31486658],
       [28.67741601],
       [37.23739763],
       [25.99294587],
       [46.38502566],
       [32.41135852],
       [26.98960859],
       [38.16338302],
       [28.24470027],
       [25.70907164],
       [29.33407484],
       [26.439885  ],
       [38.25158752],
       [39.3013865 ],
       [28.03526158],
       [32.00530701],
       [29.25608776],
       [38.16796257],
       [31.10488848],
       [29.17498107],
       [32.28969741],
       [28.46088308],
       [29.29412391],
       [37.79628131],
       [36.95430886],
       [39.39562101],
       [30.11510267],
       [38.82004185],
       [39.80527237],
       [31.25079222],
       [28.68173618],
       [27.78092758],
       [38.36644081],
       [44.22836696],
       [33.91803261],
       [30.39177731],
       [38.20141918],
       [27.92155353],
       [37.98814558],
       [36.76977326],
       [27.27940305],
       [30.06083922],
       [30.08572634],
       [27.26065976],
       [41.81979226],
       [35.3936013 ],
       [37.79628131],
       [27.95374063],
       [30.42817145],
       [26.61983269],
       [41.96353115],
       [38.77238023],
       [30.21276732],
       [38.91538501],
       [37.12651661],
       [37.41343676],
       [28.54063774],
       [36.79765383],
       [38.27693272],
       [27.40598744],
       [40.22989889],
       [27.24087678],
       [27.79581609],
       [37.21001937],
       [27.66522234],
       [36.07516918],
       [28.66990809],
       [41.22711279],
       [27.40541785],
       [28.43223881],
       [35.07123098],
       [29.20248868],
       [40.83502257],
       [37.83558697],
       [28.94856844],
       [38.66882852],
       [39.09755307],
       [40.29698262],
       [29.39550757],
       [28.37349966],
       [47.07130083],
       [27.56481073],
       [28.46749417],
       [29.15218752],
       [48.95883453],
       [40.96291028],
       [37.38034391],
       [29.48828702],
       [31.11990101],
       [27.99598382],
       [28.38615533],
       [28.46852955],
       [39.31583862],
       [39.21368344],
       [26.45871748],
       [26.85964402],
       [30.6224665 ],
       [27.07480083],
       [30.4369315 ],
       [30.17682447],
       [40.62620884],
       [26.4843071 ],
       [37.79771126],
       [28.99644002],
       [29.83370938],
       [35.58401876],
       [27.44654114],
       [28.27216568],
       [29.17154258],
       [47.25715976],
       [33.80935668],
       [32.62463211],
       [27.95794766],
       [28.26337481],
       [38.28962368],
       [31.84291471],
       [27.38412728],
       [37.70687045],
       [28.01452402],
       [26.77513836],
       [29.21579391],
       [27.66619438],
       [30.21879238],
       [32.17146544],
       [39.16955025],
       [28.62174515],
       [28.94533417],
       [29.81526659],
       [29.29412391],
       [39.19217781],
       [38.72223258],
       [26.3258111 ],
       [27.65353871],
       [28.83827807],
       [38.52604036],
       [31.21195108],
       [30.23780182],
       [29.53370797],
       [37.00823568],
       [38.30299632],
       [40.49814294],
       [37.06808225],
       [26.29071676],
       [38.6240337 ],
       [41.21456584],
       [38.67174172],
       [31.79844991],
       [27.48976511],
       [29.97082559],
       [27.99598382],
       [41.84013441],
       [30.9970274 ],
       [26.93568177],
       [28.99588081],
       [37.77171527],
       [36.81173809],
       [29.34020739],
       [28.54063774],
       [30.24768201],
       [55.10838201],
       [41.85597561],
       [39.70655479],
       [27.65282466],
       [27.46342707],
       [27.34809709],
       [36.99052908],
       [27.81116987],
       [28.75931895],
       [41.23851773],
       [28.78740963],
       [38.7633088 ],
       [26.31630638],
       [27.35423953],
       [29.33846198],
       [27.44533766],
       [27.02719344],
       [28.54063774],
       [27.58790843],
       [26.78815126],
       [28.60171621],
       [31.37245213],
       [49.80849095],
       [29.12350913],
       [41.29026564],
       [27.77181964],
       [27.28345792],
       [31.27106847],
       [31.5788444 ],
       [40.32134515],
       [34.82103446],
       [38.52597567],
       [30.26730938],
       [32.67059342],
       [37.01830935],
       [28.19741324],
       [47.89489365],
       [29.74377383],
       [37.09012248],
       [38.64855251],
       [27.70660069],
       [37.52607868],
       [40.79446887],
       [41.61590578],
       [37.8093949 ],
       [26.36969631],
       [27.30291478],
       [48.2081996 ],
       [43.94184862],
       [48.50983397],
       [31.18208607],
       [27.47092729],
       [27.72258928],
       [30.95776277],
       [32.17744342],
       [27.58283924],
       [30.20343768],
       [29.3335582 ],
       [29.03052641],
       [39.61731672],
       [38.01912208],
       [28.80156214],
       [28.53612753],
       [40.22601454],
       [38.07534685],
       [26.01875262],
       [32.81054137],
       [29.39550757],
       [36.54990904],
       [27.29869592],
       [29.16445253],
       [39.3601622 ],
       [39.14434928],
       [28.99249025],
       [29.75188452],
       [31.22459172],
       [38.39852865],
       [28.85306319],
       [27.91656932],
       [36.92896295],
       [36.91921452],
       [27.78897491],
       [39.26787761],
       [39.35303988],
       [37.48810721],
       [35.9361853 ],
       [34.5218743 ],
       [29.56694726],
       [27.29896501],
       [31.55281151],
       [40.77296325],
       [29.17753295],
       [28.91886884],
       [38.75148071],
       [27.18125367],
       [40.10266394],
       [29.63465967],
       [31.32077692],
       [29.17498156],
       [28.68490656],
       [39.95833099],
       [38.33138374],
       [30.1566949 ],
       [36.89092679],
       [25.89493057],
       [30.76474388],
       [37.08427342],
       [38.16796257],
       [47.51703412],
       [42.16166582],
       [27.31259231],
       [30.05531196],
       [28.06154674],
       [36.63071984],
       [36.99231044],
       [27.51187068],
       [29.61555896],
       [27.35867506],
       [28.71999714],
       [32.21399761],
       [31.62492788],
       [37.95420585],
       [37.40606447],
       [28.49332537],
       [36.82757929],
       [31.93831881],
       [42.40806955],
       [28.90222835],
       [36.92539723],
       [28.06639437],
       [37.90305391],
       [29.84916448],
       [28.76094054],
       [37.85972581],
       [27.77181964],
       [32.06083114],
       [28.91854328],
       [29.71711793],
       [36.56194663],
       [29.86919341],
       [28.56792166],
       [40.59846071],
       [39.64950382],
       [28.64359493],
       [54.80394281],
       [35.46169516],
       [37.92182329],
       [28.71125317],
       [29.39565617],
       [30.23780182],
       [29.7011927 ],
       [27.83512175],
       [27.08001472],
       [29.83600416],
       [27.57165191],
       [30.72380049],
       [29.087115  ],
       [41.74381921],
       [27.04197856],
       [26.48874264],
       [40.6336068 ],
       [27.12732757],
       [38.01081863],
       [38.83104261],
       [28.3764069 ],
       [39.11237395],
       [26.78988231],
       [26.49966088],
       [26.2923545 ],
       [28.5659549 ],
       [28.97437519],
       [30.48728629],
       [27.61483846],
       [46.98440752],
       [27.10830085],
       [29.30996511],
       [46.94192349],
       [36.62732929],
       [31.6553437 ],
       [40.94190167],
       [27.37895204],
       [31.71820085],
       [29.30217124],
       [30.08572634],
       [41.22267653],
       [36.88995475],
       [38.43059752],
       [35.63130207],
       [46.46213003],
       [29.8376589 ],
       [35.28503758],
       [29.73922885],
       [29.38087105],
       [35.34497106],
       [29.24633933]])

In [89]:
from sklearn.externals import joblib

In [48]:
import urllib.request
import json

In [91]:
from sklearn.externals import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(regressor, 'Accident.pkl') 
  
# Load the model from the file 
knn_from_joblib = joblib.load('Accident.pkl')  
  
# Use the loaded model to make predictions 
knn_from_joblib.predict(X_test)

array([32.5       , 37.36607143, 35.        , 30.625     , 43.75      ,
       30.        , 34.375     , 31.875     , 30.875     , 27.5       ,
       46.66666667, 30.875     , 28.125     , 55.        , 31.25      ,
       37.5       , 27.5       , 34.85714286, 35.        , 35.        ,
       30.625     , 31.25      , 34.85714286, 28.125     , 31.875     ,
       29.375     , 27.70833333, 30.        , 29.58333333, 49.5       ,
       36.875     , 28.125     , 29.375     , 34.85714286, 30.        ,
       35.625     , 31.875     , 29.375     , 26.25      , 37.36607143,
       61.875     , 38.33333333, 30.        , 30.        , 27.5       ,
       28.125     , 37.59375   , 38.75      , 38.125     , 28.75      ,
       34.16666667, 26.25      , 50.        , 32.8125    , 27.5       ,
       37.5       , 30.625     , 26.25      , 29.375     , 25.625     ,
       36.5625    , 36.91666667, 28.75      , 33.125     , 29.375     ,
       37.36607143, 32.91666667, 29.375     , 32.5       , 28.75      ,
       28.75      , 37.59375   , 34.85714286, 38.76666667, 30.625     ,
       36.875     , 38.33333333, 31.25      , 28.125     , 26.875     ,
       36.08333333, 36.25      , 33.95833333, 30.        , 37.36607143,
       27.5       , 35.        , 32.5       , 26.875     , 31.25      ,
       30.625     , 28.125     , 39.5       , 55.        , 37.59375   ,
       26.875     , 30.        , 26.25      , 55.        , 38.125     ,
       31.25      , 37.70833333, 36.        , 33.125     , 28.75      ,
       35.53571429, 37.5       , 28.82352941, 36.25      , 26.875     ,
       26.875     , 38.8125    , 28.75      , 34.375     , 28.125     ,
       39.79166667, 27.5       , 28.125     , 33.75      , 28.75      ,
       39.10714286, 37.59375   , 29.375     , 36.25      , 38.76666667,
       39.10714286, 28.75      , 27.5       , 42.5       , 28.125     ,
       30.        , 29.16666667, 55.        , 49.58333333, 38.8125    ,
       30.        , 31.875     , 26.875     , 28.125     , 28.125     ,
       37.5       , 38.76666667, 26.875     , 26.25      , 31.25      ,
       28.82352941, 30.625     , 30.        , 38.75      , 26.875     ,
       35.        , 30.625     , 29.16666667, 35.625     , 28.125     ,
       28.125     , 29.16666667, 42.5       , 32.5       , 33.125     ,
       27.5       , 28.75      , 35.        , 30.625     , 27.5       ,
       40.        , 28.75      , 27.5       , 29.375     , 28.125     ,
       30.625     , 29.375     , 38.125     , 28.75      , 28.125     ,
       29.375     , 28.75      , 38.76666667, 36.25      , 26.25      ,
       27.5       , 28.75      , 36.875     , 40.3125    , 30.625     ,
       30.        , 36.        , 36.875     , 36.91666667, 38.8125    ,
       26.25      , 36.875     , 39.375     , 38.76666667, 31.875     ,
       27.5       , 30.        , 26.875     , 39.79166667, 32.875     ,
       26.25      , 29.375     , 37.59375   , 34.85714286, 28.75      ,
       28.75      , 30.625     , 55.        , 39.79166667, 55.        ,
       28.125     , 28.125     , 27.5       , 35.95833333, 26.875     ,
       29.375     , 39.375     , 28.125     , 37.5       , 26.25      ,
       28.82352941, 29.375     , 27.5       , 27.5       , 28.75      ,
       27.5       , 26.875     , 28.75      , 31.25      , 55.        ,
       29.375     , 39.375     , 27.5       , 26.875     , 31.25      ,
       31.875     , 39.765625  , 34.375     , 35.625     , 30.        ,
       32.8125    , 34.375     , 29.375     , 42.5       , 30.        ,
       36.        , 35.        , 27.5       , 33.125     , 39.765625  ,
       37.8125    , 35.        , 25.625     , 29.375     , 46.66666667,
       50.        , 55.        , 27.29166667, 27.5       , 28.125     ,
       30.625     , 40.        , 27.5       , 30.        , 28.75      ,
       28.75      , 38.125     , 36.875     , 29.375     , 29.375     ,
       38.33333333, 34.85714286, 26.25      , 32.5       , 28.75      ,
       35.53571429, 27.5       , 29.375     , 37.8125    , 35.        ,
       29.375     , 30.        , 31.25      , 34.375     , 28.75      ,
       28.75      , 34.85714286, 34.85714286, 27.5       , 38.76666667,
       38.76666667, 35.        , 32.08333333, 35.95833333, 30.        ,
       27.5       , 27.70833333, 39.765625  , 28.75      , 28.4375    ,
       37.5       , 28.82352941, 39.10714286, 30.        , 31.875     ,
       29.16666667, 28.4375    , 37.5       , 36.875     , 30.625     ,
       35.53571429, 26.25      , 30.625     , 36.        , 37.36607143,
       50.        , 41.25      , 29.375     , 30.        , 27.5       ,
       35.625     , 35.53571429, 27.5       , 30.875     , 28.82352941,
       28.75      , 32.5       , 31.875     , 37.59375   , 55.        ,
       28.75      , 34.85714286, 32.875     , 40.625     , 28.75      ,
       35.53571429, 29.375     , 40.625     , 30.625     , 28.75      ,
       40.        , 27.5       , 40.        , 29.375     , 30.625     ,
       33.75      , 30.625     , 28.75      , 39.10714286, 42.        ,
       28.95833333, 70.        , 32.25      , 40.        , 26.875     ,
       28.4375    , 30.625     , 30.        , 26.875     , 26.875     ,
       29.375     , 27.5       , 30.625     , 29.375     , 40.        ,
       27.5       , 26.875     , 39.765625  , 26.875     , 35.        ,
       36.875     , 28.125     , 42.        , 27.5       , 26.875     ,
       26.25      , 30.        , 29.375     , 29.375     , 29.375     ,
       55.        , 27.5       , 28.75      , 36.25      , 35.53571429,
       31.875     , 39.375     , 28.125     , 31.875     , 29.375     ,
       30.625     , 39.375     , 36.        , 33.125     , 55.        ,
       55.        , 31.25      , 33.95833333, 29.375     , 28.4375    ,
       33.4375    , 29.375     ])

In [73]:
clf.predict(X_test)

array([36.5625])

In [47]:
model.dump(regressor,'Acc_Data1.pkl')

AttributeError: 'bytes' object has no attribute 'dump'

In [70]:
regressor_from_joblib = joblib.load('model.pkl')  
  
# Use the loaded model to make predictions 
regressor_from_joblib.predict(X_test)

FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

In [213]:
pwd

'C:\\Users\\user\\Accident_data'

In [60]:
import _pickle as pickle

pickle_file = open('filename.pkl')
data = pickle.load(pickle_file)

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 46: character maps to <undefined>

In [71]:
clf = joblib.load('Accident.pkl')

In [62]:
clf

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [64]:
import pandas as pd
from flask import Flask, jsonify, request
import pickle

In [55]:
# load model
with open('clf','rb') as f:
    mp=pickle.load(f)

UnpicklingError: invalid load key, '\x15'.

In [57]:
with open('Accident.pkl','wb') as fout:
    pickle.dump([1,2,3],fout)

# read data from a file
with open('Accident.pkl') as fin:
    print(pickle.load(fin))

TypeError: a bytes-like object is required, not 'str'

In [67]:
export FLASK_ENV=development
flask run

SyntaxError: invalid syntax (<ipython-input-67-d63b1d43e7a3>, line 1)

In [65]:


# load model

# app
app = Flask(__name__)

# routes
@app.route('/', methods=['POST'])

def predict():
    # get data
    data = request.get_json(force=True)

    # convert data into dataframe
    data.update((x, [y]) for x, y in data.items())
    data_df = pd.DataFrame.from_dict(data)

    # predictions
    result = clf.predict(data_df)

    # send back to browser
    output = {'results': int(result[0])}

    # return data
    return jsonify(results=output)

if __name__ == '__main__':
    app.run(port = 5000, debug=True)

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

 * Restarting with stat

SystemExit: 1

C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3333: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [66]:
%tb

SystemExit: 1

In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle 
from flask import Flask, jsonify, request
import pickle
import joblib 
dataset=pd.read_excel(r'C:\Users\user\Accident_data\Acc_data_version2 - Copy.xlsx')
dataset=dataset.drop(["State","Day","Time","Weather","Age","OVERLOAD","Vehicle_Age","COMMODITY","Cost % Of Commodity Damage","Packed_in","VEHICLE_TYPE","WEIGHT_CAPACITY(METRIC_TON)","COMMODITY WEIGHT","VEHICLE_HEALTH"],axis=1)
X=pd.DataFrame(dataset.iloc[:,:-1])
y=pd.DataFrame(dataset.iloc[:,-1])
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(min_samples_split=4,max_depth=25)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [93]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 9 columns):
Accidents risk              1337 non-null float64
Day risk scale              1337 non-null float64
Time risk scale             1337 non-null float64
Weather risk scale          1337 non-null float64
Age risk scale              1337 non-null float64
Vehicle Age risk scale      1337 non-null float64
OVERLOAD SCALE              1337 non-null int64
VEHICLE HEALTH SCALE        1337 non-null int64
ACCIDENT RISK PERCENTAGE    1337 non-null float64
dtypes: float64(7), int64(2)
memory usage: 94.1 KB

In [95]:
dataset['Accidents risk'][0]

3.5